AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: core infrastructure definitions

Parameters:
  DataBucket:
    Type: String
    Description: S3 bucket to store data
  OpenAIAPIKey:
    Type: String
    Description: OpenAI API key
  SchedulerEnabled:
    Type: String
    Description: Toggle scheduler on or off
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
  JWTSigningKey:
    Type: String
    Description: JWT signing key

Mappings:
  SchedulerToggle:
    Toggle:
      'true': true
      'false': false

Resources:
  dataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cmd/lambda/data/
      Description: function responsible for fetching and storing data
      Environment:
        Variables:
          DATA_BUCKET_NAME:
            Ref: DataBucket
          QUESTIONS_TABLE_NAME:
            Ref: questionsTable
          SUMMARIES_TABLE_NAME:
            Ref: summariesTable
          OPENAI_API_KEY:
            Ref: OpenAIAPIKey
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Description: daily check for new blog content
            Enabled:
              Fn::FindInMap:
                - SchedulerToggle
                - Toggle
                - Ref: SchedulerEnabled
            Schedule: cron(0 12 * * ? *)
      Handler: data
      MemorySize: 1024
      Policies:
        - Version: '2012-10-17' 
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource:
                Fn::Sub: arn:aws:s3:::${DataBucket}/*
            - Effect: Allow
              Action:
                - dynamodb:BatchWriteItem
                - dynamodb:Scan
              Resource:
                Fn::GetAtt:
                  - summariesTable
                  - Arn
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
              Resource:
                Fn::GetAtt:
                  - questionsTable
                  - Arn
      Runtime: go1.x
      Timeout: 30
  infoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cmd/lambda/info/
      Description: function responsible for responding to user questions
      Environment:
        Variables:
          DATA_BUCKET_NAME:
            Ref: DataBucket
          QUESTIONS_TABLE_NAME:
            Ref: questionsTable
          SUMMARIES_TABLE_NAME:
            Ref: summariesTable
          OPENAI_API_KEY:
            Ref: OpenAIAPIKey
          JWT_SIGNING_KEY:
            Ref: JWTSigningKey
      Events:
        QuestionEvent:
          Type: Api
          Properties:
            Method: POST
            Path: /question
        SummariesEvent:
          Type: Api
          Properties:
            Method: GET
            Path: /summaries
      Handler: info
      MemorySize: 512
      Policies:
        - Version: '2012-10-17' 
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource:
                Fn::Sub: arn:aws:s3:::${DataBucket}/*
            - Effect: Allow
              Action:
                - dynamodb:BatchWriteItem
                - dynamodb:Scan
              Resource:
                Fn::GetAtt:
                  - summariesTable
                  - Arn
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
              Resource:
                Fn::GetAtt:
                  - questionsTable
                  - Arn
      Runtime: go1.x
      Timeout: 15
  questionsTable:
    Type: AWS::Serverless::SimpleTable
  summariesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

Outputs:
  QuestionsTableName:
    Value:
      Ref: questionsTable
  SummariesTableName:
    Value:
      Ref: summariesTable
  DataBucketName:
    Value:
      Ref: DataBucket
  OpenAIAPIKey:
    Value:
      Ref: OpenAIAPIKey
  QuestionAPIEndpoint:
    Description: Endpoint for processing user questions
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/question
  SummariesAPIEndpoint:
    Description: Endpoint for serving essay summaries
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/summaries
